### ISSUE TITLE
Consider cloudflare R2 for storing images to send to client

### ISSUE THREAD

**Issue by db0** [db0/AI-Horde#74]
Will allow me to serve uncompressed images

https://developers.cloudflare.com/r2/data-access/s3-api/presigned-urls/

**Comment by ndahlquist** [comment]
We could also do this with Google Cloud Storage (I used it for something similar recently). 

1. On the (trusted) server, create a blob and expose an upload URL:

```python
from firebase_admin import storage, firestore

bucket = storage.bucket(name="stable_diffusion_public")
output_file_path = f"{world_id}/{uuid.uuid4()}.webp"
blob = bucket.blob(output_file_path)

upload_url = blob.generate_signed_url(
    version="v4",
    # This URL is valid for 15 minutes
    expiration=datetime.timedelta(minutes=15),
    # Allow PUT requests using this URL.
    method="PUT",
    content_type="image/webp",
)

# This URL will allow data upload via POST.
print("upload_url", upload_url)

# This URL will allow data download via GET.
print('public_url', blob.public_url)
```

2. Send the upload URL to (untrusted) 3rd parties (client or workers), which can then upload:

```
response = requests.put(
        upload_url,
        data=out_image_bytes,
        headers={
            "Content-Type": "image/webp",
        },
    )
```

3. We should configure the blobs to automatically get deleted after some time (24 hours?), so that we're not charged for storage long-term.

The big benefit of Cloudflare R2, as I understand, is you pay only for storage, not bandwidth. However, it might be worth evaluating Google Cloud and AWS too in case one of them ends up being cheaper (Google Cloud has a generous free tier- I think AWS may too).

**Comment by ndahlquist** [comment]
I believe this one can be closed now (we have the 'r2' option in the API)
